---
- hosts: all
  become: true
  vars:
    create_containers: 1
    default_container_name: nginx
    default_container_image: nginx
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Pull docker images
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
    - name: Pull docker images
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        state: started
        ports: "8080:80"
      with_sequence: count={{ create_containers }}
