- hosts: webservers
  name: Touch files in optional mode
  file:
     dest: "{{ item.path }}"
     state: touch
     mode: "{{ item.mode | default(omit) }}"
  loop:
    - path: /tmp/foo
    - path: /tmp/bar
    - path: /tmp/baz
      mode: "0444"
